Fix undercounted login times (numlogindays)
ptt/pttbbs pull request #105
Opened 2021-06-16 01:37 UTC by IepIweidieng

Relevant issue: #104

The method for increasing user's login count has been refined to prevent undercounting of the login times.
It works as follows:

* Login time increment at login (the same as the current method)

For users who haven't logged in today, increase their login count by 1 at login.

* Login time increments according to the online duration

When either `update_online` runs *or the user logs out*, if the user's online duration reaches N days (>= N⋅86400 seconds), increase the user's login count by N and the user's `lastlogin` by N days.
(Increasing `lastlogin` by N days makes the online duration decrease by N days)

Compare it to the current method:
* The online duration is not checked at logout -> is checked at logout
* Increment is performed only when the online duration *exceeds* 1 day (> 86400 seconds)
  -> is performed also when the duration reaches 1 day (= 86400 seconds)
    * Explained below as the login count increment rate issue
* The login count only increases by 1 -> can increase by N
* `lastlogin` is set to the current time (resets the online duration to 0)
  -> `lastlogin` is increased by N days (reduces the online duration by N days)
    * A reset would cause users to lose some of their online duration, enough to cause undercounting.
    * The reset method is also prone to unpredictable cron job delays.

Executing `update_online` is no longer necessary to increase users' login count but is still needed to minimize users' loss of login times due to abnormal termination of their session.

---

改進了登入次數的計算方法以避免少算。
新計算方式：

* 登入時增加登入次數（與目前計算方式相同）

如果今天還沒登入，登入時就把登入次數加一。

* 依照線上時間增加登入次數

在 `update_online` 執行時 **與在使用者登出時**，如果線上時間達到 N 天（>= N⋅86400 秒），就把登入次數加 N，並把 `lastlogin` 的時間值增加 N 天。
（把 `lastlogin` 的時間值增加 N 天會使線上時間減少 N 天）

與目前計算方法的比較：
* 登出時不檢查線上時間 -> 會檢查
* 只在線上時間 **超過** 一天（> 86400 秒）時增加登入次數
  -> 也在線上時間達到一天（= 86400 秒）時增加
    * 詳細說明請見底下的「登入次數增加速率問題」
* 登入次數一次只加一 -> 可以一次加 N
* `lastlogin` 會設成目前的時間（重設線上時間為 0）
  -> `lastlogin` 的時間值會增加 N 天（減少線上時間 N 天）
    * 線上時間的重設會造成使用者損失部份線上時間，足以造成少算。
    * 使用重設的計算方法也容易遇到 cron 排程工作有不可預期的執行延遲的問題。

不需要執行 `update_online` 來增加登入次數了。不過還是需要執行 `update_online` 來儘可能降低使用者因為其工作階段異常中止而損失登入次數的風險。

---

The login count increment rate issue resulted from the slightly flawed condition for excluding users from increment.

The condition should exclude users whose online duration < 1 day.

When `update_online` was introduced on 2014-03-25 (UTC+8), this condition was wrongly flipped as `u->lastlogin + DAY_SECONDS <= now`.
It was corrected within an hour to be `now < urec.lastlogin + DAY_SECONDS` (equivalently `urec.lastlogin + DAY_SECONDS > now`).
See commits 4f69140dc2d8 ("Add utility to update user online counter (lastlogin/numlogindays).") and 6871fbb02626 ("Update using ulist.") for details.

A 1-hour tolerance of online duration was soon introduced and cancelled.
See commit 05702e53041e ("update_online: prevent too verbose messages and allow some tolerance in duration.").

Within 1 day, another commit changed this condition to `urec.lastlogin >= base`, where `base` was defined as 09:40 of the current day (in the local time zone).
It may have meant to increase the login count for users logged in before 09:40.
This was stated to be inspired by the login time increment at login.

However, `update_online` seems to have run at 00:00 of the day at that time.
This made the condition always false since 09:40 would be a time in the future, and thus all online users' login count were increased unconditionally.
This caused overcounting of the login times, as users might manage to log in at 00:00 and before `update_online` ran, thus getting 2 login times on that day.

(Cron jobs may delay for seconds, especially when the system load is high)

See commit 05bb3eb587c1 ("Change update_online to do same way as pwcu does.") for details.

In order to address this issue, commits f1328b3dbcc4 ("Fix calculation error in update_online.", 2014-12-23 (UTC+8)) and d38b21dd0c44 ("Fix update_online again, to avoid timezone problems.", 2014-12-24 (UTC+8)) were made to redefine `base` as `time(0) - DAY_SECONDS`.
The relevant logic somehow reverted to using the logic in commit 6871fbb02626 ("Update using ulist.").

However, the condition `urec.lastlogin >= base` did not revert accordingly and became arithmetically equivalent to `urec.lastlogin + DAY_SECONDS >= now`, which does exclude users whose online duration = 1 day.

Since `update_online` runs every 1 day in the current system configuration, the users' online duration between 2 successive runs cannot exceed 1 day (assume that cron jobs have the same delay in every run).
In other words, when the users' `lastlogin` was reset in an `update_online` run, their login count would not increase in the next `update_online` run, which made their login count only increase by 1 every 2 days.

This issue is fixed by changing this condition to `urec.lastlogin > base` to allow users with online duration = 1 day to have their login count increased.

---

登入次數增加速率問題，是來自有點瑕疵的用來排除要增加其登入次數的使用者的條件式。

這個條件式應該要排除上線時間小於一天的使用者。

`update_online` 在 2014-03-25 (UTC+8) 引進時，這個條件式是效果相反的 `u->lastlogin + DAY_SECONDS <= now`，
而在一小時內就被修正成了 `now < urec.lastlogin + DAY_SECONDS`（等價於 `urec.lastlogin + DAY_SECONDS > now`）。
相關細節請見 commits 4f69140dc2d8 ("Add utility to update user online counter (lastlogin/numlogindays).") 與 6871fbb02626 ("Update using ulist.")。

不久之後，一小時的線上時間誤差容忍值就被引進，但出現不久就被取消了。
請見 commit 05702e53041e ("update_online: prevent too verbose messages and allow some tolerance in duration.")。

一天之內有另一個 commit 將此條件式修改為 `urec.lastlogin >= base`，其中 `base` 被定義為當天的 09:40（目前時區），可能原本是為了要增加在 09:40 前登入的使用者的登入次數。
有說明到說這是受到登入時增加登入次數的啟發。

但是當時 `update_online` 應該是在一天的 00:00 執行的，09:40 是未來時間，會讓這個條件式永不成立，所以線上使用者的登入次數會被無條件增加。
這會造成登入次數多算。因為使用者有可能會在 00:00 時，`update_online` 執行前登入，然後在當天拿到兩次登入。

（Cron 排程工作有可能會延遲幾秒執行，尤其是在系統負載高的時候）

相關細節請見 commit 05bb3eb587c1 ("Change update_online to do same way as pwcu does.")。

為了解決這個問題，commits f1328b3dbcc4 ("Fix calculation error in update_online.", 2014-12-23 (UTC+8)) 與 d38b21dd0c44 ("Fix update_online again, to avoid timezone problems.", 2014-12-24 (UTC+8)) 把 `base` 重新定義成 `time(0) - DAY_SECONDS`，某種程度上把相關邏輯恢復到了 commit 6871fbb02626 ("Update using ulist.") 的時候。

但是條件式 `urec.lastlogin >= base` 沒跟著恢復，結果變成在算術上等價於 `urec.lastlogin + DAY_SECONDS >= now`，會排除線上時間等於一天的使用者。

因為根據目前的系統設定，`update_online` 每天會執行一次，所以使用者在兩次執行間所累積的線上時間沒辦法超過一天（假設 cron 排程工作每次執行的延遲都一樣）。
也就是說，如果使用者的 `lastlogin` 在某次 `update_online` 執行時被重設了，那下次 `update_online` 執行時，登入次數就不會增加，結果使用者的登入次數每兩天只會增加一。

把這個條件式改成 `urec.lastlogin > base`，讓線上時間等於一天的使用者的登入次數可以增加，這個問題就解決了。

---

測試案例：
* 時間點格式：D<第幾天> <時>:<分>
* 時間長度格式：<天數>d<小時數>h<分鐘數>

事件                   | 登入        | (登出)           | 檢查點                                   | (登出)            | 檢查點/登出
 ---                     | :---:         | :---:               | :---:                                        | :---:               | :---:
時間點               | D1 23:50 | D3 00:01       | D3 04:00                                | D3 23:50       | D4 04:00
總線上時間        | 0d00h00 | 1d00h11       | 1d04h10                                | 2d00h00       | 2d04h10
舊方法檢查點    | D1 23:50 | D1 23:50       | D1 23:50 </br> -> D3 04:00 | D3 04:00       | D3 04:00
舊方法線上時間 | 0d00h00 | 1d00h11       | 1d04h10 </br> -> 0d00h00 | 0d19h50       | 1d00h00*
舊方法登入次數 | +1           | (+0; 共 +1) | +1                                          | (+0; 共 +2) | +0; 共 +2
新方法檢查點     | D1 23:50 | D1 23:50 </br> (-> D2 23:50) | D1 23:50 </br> -> D2 23:50 | D2 23:50 </br> (-> D3 23:50) | D2 23:50 </br> -> D3 23:50
新方法線上時間 | 0d00h00 | 1d00h11 </br> (-> 0d00h11)  | 1d04h10 </br> -> 0d04h10 | 1d00h00 </br> (-> 0d00h00) | 1d04h10 </br> -> 0d04h10
新方法登入次數 | +1           | (+1; 共 +2)                             | +1                                          | (+1; 共 +3)                             | +1; 共 +3

* 注意若依照舊方法，線上時間須 **超過** 1d00h00 才會增加登入次數。

2023-06-06 02:27 UTC, hungte commented
Increasing numlogindays at logout is a not a good idea because:
- When the system needs to kick out everyone, that will introduce more dirty logs we have to flush.
- Aborted sessions are sometimes more than expected.
- We are not counting "86400 seconds" because that used to lead to arguments.

2023-06-07 12:47 UTC, hungte requested changes
Please rethink about an algorithm that we won't need to write pwcu on exit.

2023-06-07 12:47 UTC, hungte commented on mbbsd/passwd.c
> +	cuser.lastlogin <= reftime - DAY_SECONDS ||
No, we should prevent writing on exit.

2023-06-08 17:19 UTC, IepIweidieng commented on mbbsd/passwd.c
> +	cuser.lastlogin <= reftime - DAY_SECONDS ||
The solution has been reworked to exclude the updating of the login count at logout. \
已重製解決方案以捨棄在登出時更動登入次數的設計。

An alternative solution is to execute `update_online` more frequently, which cannot be addressed by this PR along, see the PR description for details. \
一種替代方案是增加 `update_online` 的執行頻率，無法單被此 PR 解決，詳見 PR 敘述。

2023-06-09 15:07 UTC, hungte commented
>  suggest update_online to be run on the following timepoints every day:
> 00:00, 06:00, 12:00, & 18:00 (i.e., one run per 6 hours 也就是每隔 6 小時執行一次)

Yes increasing the frequency of update_online may reduce the issue, but running password check-like programs at rush hours (e.g, 0:00, 12:00, 18:00) is super dangerous on PTT since it will largely increase the risk of hitting passwd sync issues. That's why we previously tried to only do it on 4:00. Also there will still be people complaining about wrong calculation.

2023-12-16 13:02 UTC, IepIweidieng commented
The scope of this pull request has been reduced to address only the problem that the login times increased only 1 per 2 days.\
本拉取請求的影響範疇已限縮至僅針對登入次數每 2 天只增加 1 次的問題。

Discussions and potential solutions regarding other issues of the login time algorithm should now go to ptt/pttbbs#104 or another pull request instead.\
今後與登入次數演算法的其它方面相關的討論與潛在的解決方案應於 ptt/pttbbs#104 或另外的拉取請求提出。

2026-09-11 08:08 UTC, merged