mbbsd: “更變” to a more widely-used vocabulary
ptt/pttbbs pull request #125
Opened 2023-01-28 18:43 UTC by pan93412

這個 PR 將「更變」更改為「變更」。

雖然根據教育部辭典，[「更變」](https://dict.revised.moe.edu.tw/dictView.jsp?ID=70515&la=0&powerMode=0)和[「變更」](https://dict.revised.moe.edu.tw/dictView.jsp?ID=19108&la=0&powerMode=0)皆是「改變」、「更改」的意思，然而現今通行電腦詞彙（以 Microsoft 和 l10n_tw 的開放原始碼翻譯詞彙庫，以及）似乎不偏向使用「更變」，[導致一部分使用者認為這是誤筆。](https://t.me/moztw_general/204405)

因此這個 PR 想要將「更變」更換為更為常見的「變更」[^1]，希望可以減少使用者在收到信件時對詞彙產生的疑惑。

[^1]: 雖然暫定「變更」但應該有更適當的詞彙。本 PR 在合併前很歡迎各界人士共同研討更適合的詞彙。

2023-01-28 19:26 UTC, chhsiao1981 commented
hi @pan93412 ～

It seems like you are using big5-hkscs instead of big5?
("十" seems different～ (0xA451 vs. 0xA2CC))

2023-01-28 20:38 UTC, IepIweidieng requested changes
以下列出屬於將「更變」變更爲「變更」以外的意外變更。\
The changes which do more than changing "更變" into "變更" are listed below.

@chhsiao1981 已指出問題。不過「〸 (A2CC)」這個字元應來自 Big5-2005 而非 Big5-HKSCS。\
@chhsiao1981 has already pointed out the issue. However, the problematic character (〸; A2CC) seems to come from Big5-2005, not from Big5-HKSCS.

可利用 `git reset @~ -p mbbsd/register.c` 僅取消這些多餘修改。\
It's possible to use `git reset @~ -p mbbsd/register.c` for cancelling only the redundant changes.

2023-01-28 20:38 UTC, IepIweidieng commented on mbbsd/register.c
> +	outs("�{�ҽX�`�@����̤T�X, �S���ťզr��.\n");
有意外更改 There is an accidental change:
* 原 The original: A451 (Big5: "十", CJK UNIFIED IDEOGRAPH-5341/中日韓統合表意文字-5341)
  被意外改爲了 Has been accidentally changed into: A2CC (Big5-2003: "〸", HANGZHOU NUMERAL TEN/蘇州碼子十)

2023-01-28 20:38 UTC, IepIweidieng commented on mbbsd/register.c
> +		"�z�O�_�~���̤K���æP�N�[�ݦ����ݪO(�Y�_�п�Jn)? [y/n]:"))
問題同上：「十」被意外改爲了「〸」。
The same issue as above: The "十" has been accidentally changed into "〸".

2023-01-29 03:58 UTC, pan93412 commented on mbbsd/register.c
> +	outs("�{�ҽX�`�@����̤T�X, �S���ťզr��.\n");
Fixed!

2023-01-29 08:12 UTC, IepIweidieng approved these changes

2023-01-30 07:36 UTC, merged