correct symlink of mail for TICKET
ptt/pttbbs pull request #26
Opened 2017-09-30 08:29 UTC by holishing

For solving the issue that user will see 
```
◆ 此封信無內容。                                              [按任意鍵繼續]
```
when they read their mail for getting money by TICKET(全站樂透).
also correct weird symbolic link referring to. (`/home/bbs/home/*/{userid}/etc/ticket`)

2017-10-01 22:53 UTC, robertabcd commented
I think one issue is that file will change over time.

2017-12-20 07:48 UTC, hungte commented
Right. I remember one problem we've seen is that this caused people able to make changes to the global ticket file, for example delete records. So we'll probably not fixing it unless that is checked and solved.

2018-01-09 10:07 UTC, hungte requested changes
We can't approve this without complete testing how it impacts users when someone deletes files in his home folder.

2018-10-09 08:58 UTC, hungte commented
No updates for  10 months. Close inactive PR.

2018-10-09 08:58 UTC, closed without merging