correct some details
ptt/pttbbs pull request #35
Opened 2017-12-21 10:48 UTC by holishing

1. mbbsd: correct improper words for that innbbsd was unsupported
2. initbbs: solve the sort problem with board "Note". 
3. initbbs: BN_DIGEST(digest for whole site) is deprecated for sure. 
4. util/Makefile: let "make clean" can clean up util/shmctl (binary file)

2017-12-26 04:26 UTC, hungte requested changes
Please explain what is sort problem in commit message

2017-12-26 04:30 UTC, hungte commented on mbbsd/bbs.c
> +    getdata(2, 0, "(S/L)�o�� (Q)���H[Q] ", genbuf, 3, LCECHO);
發文 may not be appropriate. The same prompt is used by post, edit, edit special menu, send mail, edit vote list, .... etc.

 發文 may lead to confusion.

2017-12-28 05:52 UTC, holishing commented on mbbsd/bbs.c
> +    getdata(2, 0, "(S/L)�o�� (Q)���H[Q] ", genbuf, 3, LCECHO);
Maybe 存檔 or 儲存 are more appropriate, but I just try to keep the same style with a8d77d5 .
or should that commit also be revised again? I'm not sure.

2017-12-29 01:16 UTC, holishing commented
ref: 
https://github.com/ptt/pttbbs/blob/master/mbbsd/ordersong.c#L216
https://github.com/ptt/pttbbs/blob/master/mbbsd/menu.c#L32

but now the order of folders in man Note after running `initbbs` just like:
```
     1. ◎ 精華區目錄索引 (0.3k)                       每天自動更新 [12/15/17]
     2. ◆ 【點 歌 歌 本】                             SYSOP        [12/14/17]
     3. ◆ <點歌> 動態看板                             SYSOP        [12/14/17]
     4. ◆ <系統> 動態看板                             SYSOP        [12/14/17]
     5. ◆ <廣告> 動態看板                             SYSOP        [12/14/17]
     6. ◆ <新聞> 動態看板                             SYSOP        [12/14/17]
```
after tests it seem to cause problem if system load contents of `<點歌> 動態看板` first.
like banners in `MMENU` (主選單) is appearing the first ordered song by users.

2018-01-09 10:03 UTC, hungte approved these changes

2018-01-09 10:04 UTC, merged